version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: .
    ports:
      - "127.0.0.1:9082:9082"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db_postgres

  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db_postgres

volumes:
  db_postgres: